name: test_windows_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.2
  google_sign_in: ^6.0.0
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
    


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true